"""Add MitreMapping model

Revision ID: 1a7ddd4255e7
Revises: a1b2c3d4e5f6
Create Date: 2026-07-28 09:52:59.090554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7ddd4255e7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitre_id', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_mappings_id'), 'mitre_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_mappings_mitre_id'), 'mitre_mappings', ['mitre_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitre_mappings_mitre_id'), table_name='mitre_mappings')
    op.drop_index(op.f('ix_mitre_mappings_id'), table_name='mitre_mappings')
    op.drop_table('mitre_mappings')
    # ### end Alembic commands ###
