"""Add username, password, tenant_id to stands

Revision ID: 32debe6a6acc
Revises: 39c66ae25379
Create Date: 2026-07-20 14:32:00.375013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32debe6a6acc'
down_revision: Union[str, Sequence[str], None] = '39c66ae25379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stands', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('stands', sa.Column('password', sa.String(length=512), nullable=True))
    op.add_column('stands', sa.Column('tenant_id', sa.String(length=255), nullable=True))
    op.alter_column('stands', 'api_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stands', 'api_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('stands', 'tenant_id')
    op.drop_column('stands', 'password')
    op.drop_column('stands', 'username')
    # ### end Alembic commands ###
